/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { BalanceListResult, BalanceQueryRequest, BalanceQueryResult } from '@dsh-plugins/balance/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$62616c616e6365 {
    list: () => Promise<RemoteResult<BalanceListResult>>
    query: (request: BalanceQueryRequest) => Promise<RemoteResult<BalanceQueryResult>>
  }
  interface TypertRemoteMap {
    'balance/list': () => Promise<RemoteResult<BalanceListResult>>
    'balance/query': (request: BalanceQueryRequest) => Promise<RemoteResult<BalanceQueryResult>>
  }
  interface TypertRemoteNamespaceMap {
    'balance': TypertRemoteNamespace$62616c616e6365
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
