/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_balance_balance_list_result$schema = z.object({
  'accounts': z.array(z.object({
  'provider': z.string().readonly(),
  'bound': z.boolean().readonly(),
  'account': z.object({
  'vendor': z.string().readonly(),
  'label': z.string().readonly(),
  'displayName': z.string().readonly(),
  'currency': z.string().readonly(),
  'total': z.number().readonly(),
  'granted': z.number().readonly().optional(),
  'toppedUp': z.number().readonly().optional(),
  'trend': z.union([z.literal("up"), z.literal("down"), z.literal("flat"), z.literal("unknown")]).readonly(),
  'delta': z.number().readonly(),
  'updatedAt': z.number().readonly(),
  'status': z.union([z.literal("ok"), z.literal("unconfigured"), z.literal("unsupported"), z.literal("error")]).readonly(),
  'errorCode': z.string().readonly().optional(),
  'errorMessage': z.string().readonly().optional(),
}).readonly().optional(),
})).readonly(),
})
const _deepseek_ai_dsh_balance_balance_query_parameter_0$schema = z.object({
  'provider': z.string().readonly(),
  'model': z.string().readonly().optional(),
})
const _deepseek_ai_dsh_balance_balance_query_result$schema = z.object({
  'provider': z.string().readonly(),
  'bound': z.boolean().readonly(),
  'account': z.object({
  'vendor': z.string().readonly(),
  'label': z.string().readonly(),
  'displayName': z.string().readonly(),
  'currency': z.string().readonly(),
  'total': z.number().readonly(),
  'granted': z.number().readonly().optional(),
  'toppedUp': z.number().readonly().optional(),
  'trend': z.union([z.literal("up"), z.literal("down"), z.literal("flat"), z.literal("unknown")]).readonly(),
  'delta': z.number().readonly(),
  'updatedAt': z.number().readonly(),
  'status': z.union([z.literal("ok"), z.literal("unconfigured"), z.literal("unsupported"), z.literal("error")]).readonly(),
  'errorCode': z.string().readonly().optional(),
  'errorMessage': z.string().readonly().optional(),
}).readonly().optional(),
})

export const TYPERT = {
  package: '@dsh-plugins/balance',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@dsh-plugins/balance#balance/list',
      service: 'balance',
      namespace: 'balance',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-plugins/balance/types#BalanceListResult',
        schema: _deepseek_ai_dsh_balance_balance_list_result$schema,
      },
      sourceLocation: {"file":"packages/balance/balance/src/runtime.ts","line":151,"column":9},
    },
    {
      id: '@dsh-plugins/balance#balance/query',
      service: 'balance',
      namespace: 'balance',
      method: 'query',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-plugins/balance/types#BalanceQueryRequest',
            schema: _deepseek_ai_dsh_balance_balance_query_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-plugins/balance/types#BalanceQueryResult',
        schema: _deepseek_ai_dsh_balance_balance_query_result$schema,
      },
      sourceLocation: {"file":"packages/balance/balance/src/runtime.ts","line":137,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "The balance service. Providers register through {@link BalanceRuntime.register}; each registration is an effect binding every declared route and withdrawing them on disposal. A query resolves the route to a provider, the credential, then the vendor account, and folds the trend from the previous observation.",
        "summary": "The balance service.",
        "tags": [],
        "jsDoc": "/**\n * The balance service. Providers register through {@link BalanceRuntime.register};\n * each registration is an effect binding every declared route and withdrawing\n * them on disposal. A query resolves the route to a provider, the credential,\n * then the vendor account, and folds the trend from the previous observation.\n */",
        "key": "balance",
        "exportName": "BalanceRuntime",
        "members": [
          {
            "kind": "method",
            "name": "register",
            "signature": "register(provider: BalanceProvider): () => void",
            "summary": "Register one vendor's balance provider.",
            "jsDoc": "/**\n * Register one vendor's balance provider. All-or-nothing: a route already\n * bound by another registration rejects the whole set, leaving the registry\n * unchanged. Disposed with the calling fiber.\n * @param provider - the provider whose routes are bound.\n * @returns the disposer withdrawing every route this registration holds.\n */"
          },
          {
            "kind": "method",
            "name": "query",
            "signature": "@Remote('query') async query(request: BalanceQueryRequest): Promise<BalanceQueryResult>",
            "summary": "Resolve one provider route's balance through its bound vendor.",
            "jsDoc": "/**\n * Resolve one provider route's balance through its bound vendor.\n * Published as the `balance/query` Remote. Business conditions — an unbound\n * route, a missing credential, an unsupported vendor, or a vendor API failure\n * — return as {@link BalanceQueryResult} branches rather than rejecting, so\n * the UI renders them as states instead of treating them as transport faults.\n * @param request - the LLM provider route and optional model id.\n * @returns the resolved result.\n */"
          },
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote('list') async list(): Promise<BalanceListResult>",
            "summary": "List every bound provider route's balance, in registration order.",
            "jsDoc": "/**\n * List every bound provider route's balance, in registration order. The\n * multi-account dashboard view reads this; each entry goes through the same\n * credential/unsupported/error resolution as a single query, and vendors are\n * interrogated sequentially so a slow one cannot spike concurrent requests.\n * @returns one entry per bound route.\n */"
          }
        ],
        "types": [
          {
            "name": "BalanceAccount",
            "declaration": "export interface BalanceAccount {\n    readonly vendor: string;\n    readonly label: string;\n    readonly currency: string;\n    readonly total: number;\n    readonly granted?: number;\n    readonly toppedUp?: number;\n    readonly trend: BalanceTrend;\n    readonly delta: number;\n    readonly updatedAt: number;\n    readonly status: BalanceAccountStatus;\n    readonly errorCode?: string;\n    readonly errorMessage?: string;\n}"
          },
          {
            "name": "BalanceAccountData",
            "declaration": "export interface BalanceAccountData {\n    readonly currency: string;\n    readonly total: number;\n    readonly granted?: number;\n    readonly toppedUp?: number;\n    readonly label?: string;\n}"
          },
          {
            "name": "BalanceAccountStatus",
            "declaration": "export type BalanceAccountStatus = 'ok' | 'unconfigured' | 'unsupported' | 'error';"
          },
          {
            "name": "BalanceListEntry",
            "declaration": "export interface BalanceListEntry {\n    readonly provider: string;\n    readonly bound: boolean;\n    readonly account?: BalanceAccount;\n}"
          },
          {
            "name": "BalanceListResult",
            "declaration": "export interface BalanceListResult {\n    readonly accounts: readonly BalanceListEntry[];\n}"
          },
          {
            "name": "BalanceProvider",
            "declaration": "export abstract class BalanceProvider {\n    abstract readonly info: BalanceProviderInfo;\n    abstract query(credential: string, signal?: AbortSignal): Promise<BalanceAccountData>;\n}"
          },
          {
            "name": "BalanceProviderInfo",
            "declaration": "export interface BalanceProviderInfo {\n    readonly vendor: string;\n    readonly displayName: string;\n    readonly providers: readonly string[];\n    readonly credentialRef: string;\n    readonly supported: boolean;\n}"
          },
          {
            "name": "BalanceQueryRequest",
            "declaration": "export interface BalanceQueryRequest {\n    readonly provider: string;\n    readonly model?: string;\n}"
          },
          {
            "name": "BalanceQueryResult",
            "declaration": "export interface BalanceQueryResult {\n    readonly provider: string;\n    readonly bound: boolean;\n    readonly account?: BalanceAccount;\n}"
          },
          {
            "name": "BalanceTrend",
            "declaration": "export type BalanceTrend = 'up' | 'down' | 'flat' | 'unknown';"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
