#!/usr/bin/env node
/**
 * Rebuild the runtime artifacts after editing src:
 *   - host bundles (surface stubs included)  src/index.ts       -> lib/index.js (esm)
 *   - client bundles                         src/client/index.ts -> lib/client.js (ModuleLoader CJS)
 * Every package's lib/ is reproducible from `pnpm build` alone.
 * The `lib/typert.*` wire artifacts are generated by the typert codegen and
 * are NOT rebuilt here; they ship inside the balance package's lib/ as-is.
 */
import { execFileSync } from 'node:child_process'
import { createRequire } from 'node:module'
import { existsSync, readFileSync, writeFileSync, rmSync, readdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

// Resolve esbuild's platform-independent CLI entry and run it through node,
// so the script works on any platform (no hardcoded win32 binary path).
const require = createRequire(import.meta.url)
const esbuildCli = require.resolve('esbuild/bin/esbuild')
const EXTERNAL = ['@deepseek-ai/*', '@dsh-plugins/*', 'zod', 'react', 'react/*']
// Client bundles run inside the browser ModuleLoader, whose module table has
// no factory for `zod` (it is neither a platform seed word nor an injected
// shell module). The generated typert wire code imports zod, so client bundles
// must inline it instead of leaving the require external; host bundles keep it
// external and resolve it from node_modules at runtime.
const EXTERNAL_CLIENT = EXTERNAL.filter((entry) => entry !== 'zod')

function run(pkg, args) {
  execFileSync(process.execPath, [esbuildCli, ...args], { cwd: join(root, pkg), stdio: 'inherit' })
}

// Host bundles (ESM, packages external) — the merged balance plugin plus the
// surface-plugin stubs, so a fresh clone + `pnpm build` reproduces every lib/.
for (const pkg of [
  'packages/dsh-balance',
  'packages/dsh-client-ui-token-crit',
  'packages/dsh-client-ui-session-monitor',
  'packages/dsh-client-ui-widget-manager',
]) {
  run(pkg, [
    'src/index.ts',
    '--bundle', '--format=esm', '--platform=node', '--target=es2022',
    ...EXTERNAL.flatMap((e) => ['--external:' + e]),
    '--outfile=lib/index.js', '--log-level=warning',
  ])
  console.log('built ' + pkg + '/lib/index.js')
}

// Balance type surface: regenerate lib/types/* from src via tsc (js + .d.ts +
// sourcemaps), so the published declarations always match the current source
// and a fresh clone can reproduce them. The stale one-off emits from the
// three-package era are wiped first. The `lib/typert.*` wire artifacts are
// NOT produced here — they are vendored generated code committed to the repo
// (see AGENTS.md); the exports check below fails loudly if they are missing.
{
  const pkg = 'packages/dsh-balance'
  const tscCli = require.resolve('typescript/bin/tsc')
  rmSync(join(root, pkg, 'lib/types'), { recursive: true, force: true })
  rmSync(join(root, pkg, 'lib/invariant.js'), { force: true })
  execFileSync(process.execPath, [tscCli, '-p', join(root, pkg, 'tsconfig.build.json')], { stdio: 'inherit' })
  // tsc rewrites `.ts` specifiers to `.js` in the JS emit but (as of TS 5.9)
  // leaves them untouched in the declaration emit. Normalize the .d.ts files
  // so consumers resolve the shipped declarations in any moduleResolution
  // mode — `./x.ts` only exists as a source-relative specifier, so the plain
  // suffix rewrite is safe.
  const dtsRoot = join(root, pkg, 'lib/types')
  for (const entry of readdirSync(dtsRoot, { recursive: true, withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.endsWith('.d.ts')) continue
    const file = join(entry.parentPath, entry.name)
    const content = readFileSync(file, 'utf8')
    const rewritten = content.replaceAll(/\.ts(['"])/g, '.js$1')
    if (rewritten !== content) writeFileSync(file, rewritten)
  }
  console.log('built ' + pkg + '/lib/types (tsc emit)')
}

// Balance plugin client bundle: CJS + inlined CSS, wrapped in the ModuleLoader
// factory shape (mounts the balance Remote, registers the dashboard + the
// providers config panel).
{
  const pkg = 'packages/dsh-balance'
  run(pkg, [
    'src/client/index.ts',
    '--bundle', '--format=cjs', '--platform=browser', '--target=es2022',
    '--jsx=automatic',
    '--loader:.css=local-css',
    ...EXTERNAL_CLIENT.flatMap((e) => ['--external:' + e]),
    '--outfile=lib/client.cjs', '--log-level=warning',
  ])
  const code = readFileSync(join(root, pkg, 'lib/client.cjs'), 'utf8')
  const css = readFileSync(join(root, pkg, 'lib/client.css'), 'utf8')
  const banner = 'window.__ModuleLoader__.load({\n\tid: "@dsh-plugins/balance",\n\tfactory: (require) => {\n\t\tvar module = { exports: {} };\n\t\tvar exports = module.exports;\n\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });\n'
  const cssInject = `\n\t\tif (typeof document !== "undefined") {\n\t\t\tvar __balanceStyleId = "@dsh-plugins/balance/styles";\n\t\t\tif (!document.querySelector("style[data-plugin-css=" + JSON.stringify(__balanceStyleId) + "]")) {\n\t\t\t\tvar __balanceStyleTag = document.createElement("style");\n\t\t\t\t__balanceStyleTag.dataset.plugin = "@dsh-plugins/balance";\n\t\t\t\t__balanceStyleTag.dataset.pluginCss = __balanceStyleId;\n\t\t\t\t__balanceStyleTag.textContent = ${JSON.stringify(css)};\n\t\t\t\tdocument.head.appendChild(__balanceStyleTag);\n\t\t\t}\n\t\t}\n`
  const footer = '\n\t\treturn module.exports;\n\t}\n});\n'
  writeFileSync(join(root, pkg, 'lib/client.js'), banner + code + cssInject + footer)
  rmSync(join(root, pkg, 'lib/client.cjs'))
  rmSync(join(root, pkg, 'lib/client.css'))
  console.log('built ' + pkg + '/lib/client.js')
}

// Token-crit client bundle: CJS + inlined CSS, wrapped in the ModuleLoader factory shape.
{
  const pkg = 'packages/dsh-client-ui-token-crit'
  run(pkg, [
    'src/client/index.ts',
    '--bundle', '--format=cjs', '--platform=browser', '--target=es2022',
    '--jsx=automatic',
    '--loader:.css=local-css',
    ...EXTERNAL_CLIENT.flatMap((e) => ['--external:' + e]),
    '--outfile=lib/client.cjs', '--log-level=warning',
  ])
  const code = readFileSync(join(root, pkg, 'lib/client.cjs'), 'utf8')
  const css = readFileSync(join(root, pkg, 'lib/client.css'), 'utf8')
  const banner = 'window.__ModuleLoader__.load({\n\tid: "@dsh-plugins/client-ui-token-crit",\n\tfactory: (require) => {\n\t\tvar module = { exports: {} };\n\t\tvar exports = module.exports;\n\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });\n'
  const cssInject = `\n\t\tif (typeof document !== "undefined") {\n\t\t\tvar __tcritStyleId = "@dsh-plugins/client-ui-token-crit/styles";\n\t\t\tif (!document.querySelector("style[data-plugin-css=" + JSON.stringify(__tcritStyleId) + "]")) {\n\t\t\t\tvar __tcritStyleTag = document.createElement("style");\n\t\t\t\t__tcritStyleTag.dataset.plugin = "@dsh-plugins/client-ui-token-crit";\n\t\t\t\t__tcritStyleTag.dataset.pluginCss = __tcritStyleId;\n\t\t\t\t__tcritStyleTag.textContent = ${JSON.stringify(css)};\n\t\t\t\tdocument.head.appendChild(__tcritStyleTag);\n\t\t\t}\n\t\t}\n`
  const footer = '\n\t\treturn module.exports;\n\t}\n});\n'
  writeFileSync(join(root, pkg, 'lib/client.js'), banner + code + cssInject + footer)
  rmSync(join(root, pkg, 'lib/client.cjs'))
  rmSync(join(root, pkg, 'lib/client.css'))
  console.log('built ' + pkg + '/lib/client.js')
}

// Widget-manager client bundle: CJS + inlined CSS, wrapped in the ModuleLoader factory shape.
{
  const pkg = 'packages/dsh-client-ui-widget-manager'
  run(pkg, [
    'src/client/index.ts',
    '--bundle', '--format=cjs', '--platform=browser', '--target=es2022',
    '--jsx=automatic',
    '--loader:.css=local-css',
    ...EXTERNAL_CLIENT.flatMap((e) => ['--external:' + e]),
    '--outfile=lib/client.cjs', '--log-level=warning',
  ])
  const code = readFileSync(join(root, pkg, 'lib/client.cjs'), 'utf8')
  const css = readFileSync(join(root, pkg, 'lib/client.css'), 'utf8')
  const banner = 'window.__ModuleLoader__.load({\n\tid: "@dsh-plugins/client-ui-widget-manager",\n\tfactory: (require) => {\n\t\tvar module = { exports: {} };\n\t\tvar exports = module.exports;\n\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });\n'
  const cssInject = `\n\t\tif (typeof document !== "undefined") {\n\t\t\tvar __wmStyleId = "@dsh-plugins/client-ui-widget-manager/styles";\n\t\t\tif (!document.querySelector("style[data-plugin-css=" + JSON.stringify(__wmStyleId) + "]")) {\n\t\t\t\tvar __wmStyleTag = document.createElement("style");\n\t\t\t\t__wmStyleTag.dataset.plugin = "@dsh-plugins/client-ui-widget-manager";\n\t\t\t\t__wmStyleTag.dataset.pluginCss = __wmStyleId;\n\t\t\t\t__wmStyleTag.textContent = ${JSON.stringify(css)};\n\t\t\t\tdocument.head.appendChild(__wmStyleTag);\n\t\t\t}\n\t\t}\n`
  const footer = '\n\t\treturn module.exports;\n\t}\n});\n'
  writeFileSync(join(root, pkg, 'lib/client.js'), banner + code + cssInject + footer)
  rmSync(join(root, pkg, 'lib/client.cjs'))
  rmSync(join(root, pkg, 'lib/client.css'))
  console.log('built ' + pkg + '/lib/client.js')
}

// Session-monitor client bundle: CJS + inlined CSS, wrapped in the ModuleLoader factory shape.
{
  const pkg = 'packages/dsh-client-ui-session-monitor'
  run(pkg, [
    'src/client/index.ts',
    '--bundle', '--format=cjs', '--platform=browser', '--target=es2022',
    '--jsx=automatic',
    '--loader:.css=local-css',
    ...EXTERNAL_CLIENT.flatMap((e) => ['--external:' + e]),
    '--outfile=lib/client.cjs', '--log-level=warning',
  ])
  const code = readFileSync(join(root, pkg, 'lib/client.cjs'), 'utf8')
  const css = readFileSync(join(root, pkg, 'lib/client.css'), 'utf8')
  const banner = 'window.__ModuleLoader__.load({\n\tid: "@dsh-plugins/client-ui-session-monitor",\n\tfactory: (require) => {\n\t\tvar module = { exports: {} };\n\t\tvar exports = module.exports;\n\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });\n'
  const cssInject = `\n\t\tif (typeof document !== "undefined") {\n\t\t\tvar __smonStyleId = "@dsh-plugins/client-ui-session-monitor/styles";\n\t\t\tif (!document.querySelector("style[data-plugin-css=" + JSON.stringify(__smonStyleId) + "]")) {\n\t\t\t\tvar __smonStyleTag = document.createElement("style");\n\t\t\t\t__smonStyleTag.dataset.plugin = "@dsh-plugins/client-ui-session-monitor";\n\t\t\t\t__smonStyleTag.dataset.pluginCss = __smonStyleId;\n\t\t\t\t__smonStyleTag.textContent = ${JSON.stringify(css)};\n\t\t\t\tdocument.head.appendChild(__smonStyleTag);\n\t\t\t}\n\t\t}\n`
  const footer = '\n\t\treturn module.exports;\n\t}\n});\n'
  writeFileSync(join(root, pkg, 'lib/client.js'), banner + code + cssInject + footer)
  rmSync(join(root, pkg, 'lib/client.cjs'))
  rmSync(join(root, pkg, 'lib/client.css'))
  console.log('built ' + pkg + '/lib/client.js')
}

// Exports completeness check: every `exports` target (default + types
// conditions) must exist after the build. Neither `pnpm pack` nor
// `git diff --exit-code` validates exports targets against the tarball, so a
// missing file (e.g. the vendored typert.* artifacts on a fresh clone) would
// otherwise ship a broken package silently.
{
  const pkgs = [
    'packages/dsh-balance',
    'packages/dsh-client-ui-token-crit',
    'packages/dsh-client-ui-session-monitor',
    'packages/dsh-client-ui-widget-manager',
    'bundles/dsh-widgets-plugin',
  ]
  const failures = []
  for (const pkg of pkgs) {
    const manifest = JSON.parse(readFileSync(join(root, pkg, 'package.json'), 'utf8'))
    const exportsMap = manifest.exports
    if (exportsMap === undefined) continue
    for (const [subpath, target] of Object.entries(exportsMap)) {
      if (subpath === './package.json') continue
      const entries = typeof target === 'string' ? { default: target } : target
      for (const [condition, file] of Object.entries(entries)) {
        if (typeof file !== 'string') continue
        if (!existsSync(join(root, pkg, file))) {
          failures.push(`${pkg} exports["${subpath}"].${condition} -> ${file} (missing)`)
        }
      }
    }
  }
  if (failures.length > 0) {
    console.error('ERROR: exported files are missing — a published tarball would be broken:')
    for (const line of failures) console.error('  ' + line)
    process.exit(1)
  }
  console.log('exports completeness: ok')
}
