#!/usr/bin/env node
/**
 * Rebuild the runtime artifacts after editing src:
 *   - host bundles (surface stubs included)  src/index.ts       -> lib/index.js (esm, esbuild)
 *   - client bundles                         src/client/index.ts -> lib/client.js (ModuleLoader CJS,
 *     built by Vite library mode, mirroring the official deepseek-harness web toolchain)
 * Every package's lib/ is reproducible from `pnpm build` alone.
 * The `lib/typert.*` wire artifacts are generated by the typert codegen and
 * are NOT rebuilt here; they ship inside the balance package's lib/ as-is.
 */
import { execFileSync } from 'node:child_process'
import { createRequire } from 'node:module'
import { existsSync, readFileSync, writeFileSync, rmSync, readdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { build as viteBuild } from 'vite'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

// Resolve esbuild's platform-independent CLI entry and run it through node,
// so the script works on any platform (no hardcoded win32 binary path).
const require = createRequire(import.meta.url)
const esbuildCli = require.resolve('esbuild/bin/esbuild')
const EXTERNAL = ['@deepseek-ai/*', '@dsh-plugins/*', 'zod', 'react', 'react/*']
// Client bundles run inside the browser ModuleLoader, whose module table has
// no factory for `zod` (it is neither a platform seed word nor an injected
// shell module). The generated typert wire code imports zod, so client bundles
// must inline it instead of leaving the require external; host bundles keep it
// external and resolve it from node_modules at runtime.
const EXTERNAL_CLIENT = EXTERNAL.filter((entry) => entry !== 'zod')

function run(pkg, args) {
  execFileSync(process.execPath, [esbuildCli, ...args], { cwd: join(root, pkg), stdio: 'inherit' })
}

// Host bundles (ESM, packages external) — the merged balance plugin plus the
// surface-plugin stubs, so a fresh clone + `pnpm build` reproduces every lib/.
for (const pkg of [
  'packages/dsh-balance',
  'packages/dsh-client-ui-token-crit',
  'packages/dsh-client-ui-session-monitor',
  'packages/dsh-client-ui-widget-manager',
]) {
  run(pkg, [
    'src/index.ts',
    '--bundle', '--format=esm', '--platform=node', '--target=es2022',
    ...EXTERNAL.flatMap((e) => ['--external:' + e]),
    '--outfile=lib/index.js', '--log-level=warning',
  ])
  console.log('built ' + pkg + '/lib/index.js')
}

// Balance type surface: regenerate lib/types/* from src via tsc (js + .d.ts +
// sourcemaps), so the published declarations always match the current source
// and a fresh clone can reproduce them. The stale one-off emits from the
// three-package era are wiped first. The `lib/typert.*` wire artifacts are
// NOT produced here — they are vendored generated code committed to the repo
// (see AGENTS.md); the exports check below fails loudly if they are missing.
{
  const pkg = 'packages/dsh-balance'
  const tscCli = require.resolve('typescript/bin/tsc')
  rmSync(join(root, pkg, 'lib/types'), { recursive: true, force: true })
  rmSync(join(root, pkg, 'lib/invariant.js'), { force: true })
  execFileSync(process.execPath, [tscCli, '-p', join(root, pkg, 'tsconfig.build.json')], { stdio: 'inherit' })
  // tsc rewrites `.ts` specifiers to `.js` in the JS emit but (as of TS 5.9)
  // leaves them untouched in the declaration emit. Normalize the .d.ts files
  // so consumers resolve the shipped declarations in any moduleResolution
  // mode — `./x.ts` only exists as a source-relative specifier, so the plain
  // suffix rewrite is safe.
  const dtsRoot = join(root, pkg, 'lib/types')
  for (const entry of readdirSync(dtsRoot, { recursive: true, withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.endsWith('.d.ts')) continue
    const file = join(entry.parentPath, entry.name)
    const content = readFileSync(file, 'utf8')
    const rewritten = content.replaceAll(/\.ts(['"])/g, '.js$1')
    if (rewritten !== content) writeFileSync(file, rewritten)
  }
  console.log('built ' + pkg + '/lib/types (tsc emit)')
}

// Client bundles (ModuleLoader CJS + inlined CSS), built with Vite library
// mode — the same toolchain the official deepseek-harness web app uses. Vite
// compiles CSS Modules natively (hashed class map in the bundle, css text
// extracted to lib/client.css), and the function external keeps react, the
// @deepseek-ai/* platform modules and @dsh-plugins/* peers as bare require()
// calls resolved from the loader module table at runtime; zod is NOT external
// and gets inlined (the ModuleLoader has no zod factory).
const CLIENT_PACKAGES = [
  { pkg: 'packages/dsh-balance', id: '@dsh-plugins/balance' },
  { pkg: 'packages/dsh-client-ui-token-crit', id: '@dsh-plugins/client-ui-token-crit' },
  { pkg: 'packages/dsh-client-ui-session-monitor', id: '@dsh-plugins/client-ui-session-monitor' },
  { pkg: 'packages/dsh-client-ui-widget-manager', id: '@dsh-plugins/client-ui-widget-manager' },
]

/** Exact-glob matcher over the EXTERNAL_CLIENT list (function form, so Vite's
 * rollupOptions.external treats them as bare-specifier externals). */
function isClientExternal(id) {
  return EXTERNAL_CLIENT.some((entry) =>
    entry.endsWith('/*') ? id.startsWith(entry.slice(0, -1)) : id === entry,
  )
}

/** Wrap a Vite CJS lib output in the ModuleLoader factory shape + CSS injection. */
function wrapModuleLoader(id, code, css) {
  const banner = 'window.__ModuleLoader__.load({\n\tid: ' + JSON.stringify(id) + ',\n\tfactory: (require) => {\n\t\tvar module = { exports: {} };\n\t\tvar exports = module.exports;\n\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });\n'
  const cssInject = `\n\t\tif (typeof document !== "undefined") {\n\t\t\tvar __styleId = ${JSON.stringify(id + '/styles')};\n\t\t\tif (!document.querySelector("style[data-plugin-css=" + JSON.stringify(__styleId) + "]")) {\n\t\t\t\tvar __styleTag = document.createElement("style");\n\t\t\t\t__styleTag.dataset.plugin = ${JSON.stringify(id)};\n\t\t\t\t__styleTag.dataset.pluginCss = __styleId;\n\t\t\t\t__styleTag.textContent = ${JSON.stringify(css)};\n\t\t\t\tdocument.head.appendChild(__styleTag);\n\t\t\t}\n\t\t}\n`
  const footer = '\n\t\treturn module.exports;\n\t}\n});\n'
  return banner + code + cssInject + footer
}

async function buildClientBundle({ pkg, id }) {
  const pkgDir = join(root, pkg)
  await viteBuild({
    // No per-package config file: the inline config below is the whole build.
    configFile: false,
    root: pkgDir,
    logLevel: 'warn',
    build: {
      outDir: 'lib',
      emptyOutDir: false, // lib/ also holds host index.js + typert.* — never wipe it
      target: 'es2022',
      minify: false,
      sourcemap: false,
      lib: {
        entry: 'src/client/index.ts',
        formats: ['cjs'],
        fileName: 'client',
      },
      rollupOptions: {
        external: isClientExternal,
      },
    },
    esbuild: {
      // automatic JSX runtime, same as the previous esbuild --jsx=automatic
      jsx: 'automatic',
    },
  })
  const code = readFileSync(join(pkgDir, 'lib/client.cjs'), 'utf8')
  const css = existsSync(join(pkgDir, 'lib/client.css')) ? readFileSync(join(pkgDir, 'lib/client.css'), 'utf8') : ''
  writeFileSync(join(pkgDir, 'lib/client.js'), wrapModuleLoader(id, code, css))
  rmSync(join(pkgDir, 'lib/client.cjs'))
  rmSync(join(pkgDir, 'lib/client.css'))
  console.log('built ' + pkg + '/lib/client.js (vite lib mode)')
}

for (const entry of CLIENT_PACKAGES) {
  await buildClientBundle(entry)
}

// Exports completeness check: every `exports` target (default + types
// conditions) must exist after the build. Neither `pnpm pack` nor
// `git diff --exit-code` validates exports targets against the tarball, so a
// missing file (e.g. the vendored typert.* artifacts on a fresh clone) would
// otherwise ship a broken package silently.
{
  const pkgs = [
    'packages/dsh-balance',
    'packages/dsh-client-ui-token-crit',
    'packages/dsh-client-ui-session-monitor',
    'packages/dsh-client-ui-widget-manager',
    'bundles/dsh-widgets-plugin',
  ]
  const failures = []
  for (const pkg of pkgs) {
    const manifest = JSON.parse(readFileSync(join(root, pkg, 'package.json'), 'utf8'))
    const exportsMap = manifest.exports
    if (exportsMap === undefined) continue
    for (const [subpath, target] of Object.entries(exportsMap)) {
      if (subpath === './package.json') continue
      const entries = typeof target === 'string' ? { default: target } : target
      for (const [condition, file] of Object.entries(entries)) {
        if (typeof file !== 'string') continue
        if (!existsSync(join(root, pkg, file))) {
          failures.push(`${pkg} exports["${subpath}"].${condition} -> ${file} (missing)`)
        }
      }
    }
  }
  if (failures.length > 0) {
    console.error('ERROR: exported files are missing — a published tarball would be broken:')
    for (const line of failures) console.error('  ' + line)
    process.exit(1)
  }
  console.log('exports completeness: ok')
}
